# Generated by Django 3.1.7 on 2021-04-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('url', models.URLField(unique=True)),
                ('image', models.URLField()),
                ('date_publish', models.CharField(max_length=30)),
                ('source_domain', models.CharField(max_length=50)),
            ],
        ),
    ]
