# Generated by Django 3.1.7 on 2021-04-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_publish',
            field=models.DateTimeField(),
        ),
    ]
