# Generated by Django 3.1.7 on 2021-04-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210417_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='date_publish',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
